#!/bin/bash

mkdir -p build

cd build

C_COMMON="-O3 -g -march=$arch"
cmake -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_POSITION_INDEPENDENT_CODE=FALSE -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_TOOLCHAIN_PREFIX=llvm- -DBUILD_BLS_PYTHON_BINDINGS=false -DBUILD_BLS_TESTS=false -DBUILD_BLS_BENCHMARKS=false -Dsodium_USE_STATIC_LIBS=ON -DCMAKE_CXX_FLAGS="${C_COMMON}" -DCMAKE_C_FLAGS="${C_COMMON}" -DARITH="gmp" -DSHLIB=on ..

make -j8 chia_plot

